title: Swetha V.S. Kolluru
theme: "minima"

# Optional: top navigation links
header_pages:
  - index.md
  - reptiles.md
  - publications.md
  - posts.md

description:
- [venkata-saiswetha.kolluru@cea.fr](mailto:venkata-saiswetha.kolluru@cea.fr)
- [Youtube](https://www.youtube.com/@saiswetha8664) 


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

