title: Swetha V.S. Kolluru
author: Swetha V.S. Kolluru
email: venkata.saiswetha-kolluru@cea.fr
theme: "minima"

# Optional: top navigation links
header_pages:
  - index.md
  - reptiles.md
  - publications.md
  - posts.md

description: >-
  Personal page â€” research, notes, and updates.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

