title: Swetha V.S. Kolluru
author: Swetha V.S. Kolluru
email: venkata.saiswetha-kolluru@cea.fr
theme: minima

# Optional: top navigation links
header_pages:
  - reptiles.md

description: >-
  Personal page â€” research, notes, and updates.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
