title: Swetha V.S. Kolluru
theme: minima

# Optional: top navigation links
header_pages:
  - [Home](index.md)
  - reptiles.md
  - publications.md
  - posts.md
  - contact.md
  
minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/saik96"
    - platform: youtube
      user_url: "https://www.youtube.com/@saiswetha8664"
    - platform: email
      user_url: "mailto:venkata-saiswetha.kolluru@cea.fr"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

