title: Swetha V.S. Kolluru
theme: minima

# Optional: top navigation links
header_pages:
  - index.md
  - reptiles.md
  - publications.md
  - posts.md

minima:
minima:
  social_links:
    YouTube: "https://www.youtube.com/@saiswetha8664"
    github: "https://github.com/saik96"
    email: "venkata-saiswetha.kolluru@cea.fr"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

